### ISSUE TITLE
Pro version

### ISSUE THREAD

**Issue by john916zhang** [stewartmcgown/vue-argon-dashboard-typescript#3]
Hi there,

I have a Pro version for this theme. I'm interested in converting it into TypeScript like you did. Can you share some tips on how to do it?

Thanks.

**Comment by stewartmcgown** [comment]
Use find, rename on Unix or Powershell on Windows to iterate through the directory and rename every .js file to .tsx. Create a tsconfig.json with some good defaults (the one in this repo is _okay-ish_) and then let VSCode show you all the problems!

**Comment by john916zhang** [comment]
Thank you so much.
